<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    </PropertyGroup>
    <PropertyGroup>
        <CompilerVersion>5.3.0</CompilerVersion>
        <DotnetVersion>10.0.10</DotnetVersion>
        <VerifyVersion>31.27.0</VerifyVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Parlot" Version="1.5.8"/>
        <PackageVersion Include="SnmpSharpNet" Version="0.9.7"/>
        <PackageVersion Include="BenchmarkDotNet" Version="0.15.8"/>
        <PackageVersion Include="TUnit" Version="1.61.38"/>
        <PackageVersion Include="Microsoft.Build" Version="$(BuildVersion)" ExcludeAssets="runtime"/>
        <PackageVersion Include="Microsoft.CodeAnalysis.Common" Version="$(CompilerVersion)"/>
        <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="$(CompilerVersion)"/>
        <PackageVersion Include="Microsoft.CodeAnalysis" Version="$(CompilerVersion)"/>
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="$(CompilerVersion)"/>
        <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="$(CompilerVersion)"/>
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="$(CompilerVersion)"/>
        <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="$(CompilerVersion)"/>
        <PackageVersion Include="Microsoft.Build.Framework" Version="$(BuildVersion)"/>
        <PackageVersion Include="Microsoft.Build.Tasks.Core" Version="$(BuildVersion)"/>
        <PackageVersion Include="Microsoft.Build.Utilities.Core" Version="$(BuildVersion)"/>
        <PackageVersion Include="Microsoft.NET.StringTools" Version="$(BuildVersion)"/>
        <PackageVersion Include="Microsoft.Extensions.Configuration" Version="$(DotnetVersion)"/>
        <PackageVersion Include="Microsoft.Extensions.Logging" Version="$(DotnetVersion)"/>
        <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="$(DotnetVersion)"/>
        <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="$(DotnetVersion)"/>
    </ItemGroup>
</Project>