<Project>
    <PropertyGroup>
        <AssemblyVersion>1.1.4</AssemblyVersion>
        <FileVersion>1.1.4</FileVersion>
        <InformationalVersion>1.1.4</InformationalVersion>
        <Version>$(AssemblyVersion)-wmo1</Version>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>
</Project>
