<Project>
    <PropertyGroup>
        <AssemblyVersion>1.2.1</AssemblyVersion>
        <FileVersion>1.2.1</FileVersion>
        <InformationalVersion>1.2.1</InformationalVersion>
        <Version>$(AssemblyVersion)-wmo1</Version>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>
</Project>
