<Project>
    <PropertyGroup>
        <AssemblyVersion>1.2.0</AssemblyVersion>
        <FileVersion>1.2.0</FileVersion>
        <InformationalVersion>1.2.0</InformationalVersion>
        <Version>$(AssemblyVersion)-wmo1</Version>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>
</Project>
