
using System.Collections.Generic;
using System.Linq;

namespace SnmpSharpNet.Mib.SourceGenerator;

public static class Templating
{
    public static string[] DocComment(string content)
    {
        return [
            $"/// <summary>",
            $"/// Generated by SnmpSharpNet.Mib.SourceGenerator",
            $"/// {content}",
            $"/// </summary>"
        ];
    }

    public static string[] TableEntry(string accessibility, MibTable table)
    {
        return [
            $"",
            $"{accessibility} class {table.EntryType()}",
            $"{{",
            $"\tpublic static readonly Oid TableRoot = {table.Ident.AsLiteral()};",
            ..table.Index.SelectMany((idx, i) => (string[])[
                $"",
                ..DocComment($"Index #{i+1}"),
                $"public required {idx.Type.AsUintType()} Index{idx.Ident.CSharpName()};",
            ]).Indent(),
            $"",
            /*$"",
            $"\tpublic required uint[] index;",
            $"",*/
            ..table.Columns.SelectMany((col, i) => (string[])[
                $"",
                ..DocComment($"Column #{i+1}"),
                $"public required {col.Type.AsAsnType()} {col.Ident.CSharpName()};",
            ]).Indent(),
            $"",
            ..EntryFromValues(table).Indent(),
            $"",
            ..TableFromValues(table).Indent(),
            $"",
            ..EntryToValues(table).Indent(),
            $"",
            ..TableToValues(table).Indent(),
            $"}}"
        ];
    }

    public static string[] EntryFromValues(MibTable table)
    {
        var indexPart = table.Index.SelectMany((index, i) => {
            var isLast = i == table.Index.Length - 1;
            if (index.IsImplied && index.Type.UintCount is null)
            {
                // IMPLIED: no length prefix, consume the rest of the index span
                return (string[])[
                    $"var index{index.Ident.CSharpName()} = ({index.Type.AsUintType()})index.ToArray();",
                    $"index = default;"
                ];
            }
            if (index.Type.UintCount is null)
            {
                return (string[])[
                    $"var index{index.Ident.CSharpName()} = ({index.Type.AsUintType()})index[1..(int)(1+index[0])].ToArray();",
                    $"index = index[(int)(1+index[0])..];"
                ];
            }
            else if (index.Type.UintCount == 1)
            {
                return (string[])[
                    $"var index{index.Ident.CSharpName()} = index[0];",
                    $"index = index[1..];"
                ];
            }
            else
            {
                return (string[])[
                    $"var index{index.Ident.CSharpName()} = ({index.Type.AsUintType()})index[..(int){index.Type.UintCount}].ToArray();",
                    $"index = index[(int){index.Type.UintCount}..];"
                ];
            }
        });



        return [
            $"public static {table.EntryType()}? EntryFromValues(ReadOnlySpan<uint> index, IReadOnlyDictionary<uint, AsnType> values)",
            $"{{",
            ..indexPart.Indent(),
            $"",
            ..table.Columns.SelectMany((col, i) => (string[])[
                $"if(!values.TryGetValue({col.Ident.Oid.Last()}, out var _{col.Ident.CSharpName()})) {{ return null; }}",
                $"if(_{col.Ident.CSharpName()} is not {col.Type.AsAsnType()} {col.Ident.CSharpName()}) {{ return null; }}",
            ]).Indent(),
            $"",
            $"\treturn new {table.EntryType()}()",
            $"\t{{",
            ..table.Index.Select(x => $"\t\tIndex{x.Ident.CSharpName()} = index{x.Ident.CSharpName()},"),
            ..table.Columns.Select(x => $"\t\t{x.Ident.CSharpName()} = {x.Ident.CSharpName()},"),
            $"\t}};",
            $"}}"
        ];
    }

    public static string[] TableFromValues(MibTable table)
    {
        var hasVariableLengthIndex = table.Index.Any(x => x.Type.UintCount is null);
        // For fixed-length indexes we can compute the exact expected OID depth.
        // For variable-length indexes (OctetString, OID, etc.) the depth varies
        // per row, so we only require that the OID is longer than entry+column.
        var depthCheck = hasVariableLengthIndex
            ? $"\tvar minDepth = entryDepth + 2;"  // at least column + 1 index component
            : $"\tvar minDepth = entryDepth + 1 + {table.Index.Sum(x => x.Type.UintCount!.Value)};";

        return [
            $"public static {table.TableType()} TableFromValues(IReadOnlyDictionary<Oid, AsnType> values)",
            $"{{",
            $"\t// OID layout: TableRoot.1.<column>.<index...>",
            $"\tvar entryDepth = TableRoot.Length + 1;",
            depthCheck,
            $"\tvar relevantValues = values",
            $"\t\t.Where(kv => kv.Key.Length >= minDepth && TableRoot.IsRootOf(kv.Key));",
            $"",
            $"\tvar entries = new Dictionary<Oid, Dictionary<uint, AsnType>>();",
            $"",
            $"\tforeach (var kv in relevantValues)",
            $"\t{{",
            $"\t\tvar path = kv.Key.ToArray();",
            $"\t\tvar column = path[entryDepth];",
            $"\t\tvar index = new Oid(path[(entryDepth + 1)..]);",
            $"\t\tif (!entries.ContainsKey(index))",
            $"\t\t{{",
            $"\t\t\tentries[index] = new();",
            $"\t\t}}",
            $"\t\tentries[index].Add(column, kv.Value);",
            $"\t}}",
            $"",
            $"\treturn entries",
            $"\t\t.Select(x => EntryFromValues((uint[])x.Key, x.Value))",
            $"\t\t.OfType<{table.EntryType()}>()",
            $"\t\t.ToArray();",
            $"}}"
        ];
    }
    public static string[] EntryToValues(MibTable table)
    {
        var indexParts = table.Index.SelectMany(index => {
            if (index.IsImplied && index.Type.UintCount is null)
            {
                // IMPLIED: no length prefix
                return (string[])[
                    $"indexOid.AddRange(Index{index.Ident.CSharpName()});"
                ];
            }
            if (index.Type.UintCount is null)
            {
                return (string[])[
                    $"indexOid.Add((uint)Index{index.Ident.CSharpName()}.Length);",
                    $"indexOid.AddRange(Index{index.Ident.CSharpName()});"
                ];
            }
            else if (index.Type.UintCount == 1)
            {
                return (string[])[
                    $"indexOid.Add(Index{index.Ident.CSharpName()});"
                ];
            }
            else
            {
                return (string[])[
                    $"indexOid.AddRange(Index{index.Ident.CSharpName()});"
                ];
            }
        });

        return [
            $"public IDictionary<Oid, AsnType> EntryToValues()",
            $"{{",
            $"\tvar indexOid = new List<uint>();",
            ..indexParts.Indent(),
            $"\tvar result = new Dictionary<Oid, AsnType>();",
            ..table.Columns.Select(col =>
                $"\tresult[new Oid((uint[])[..TableRoot, 1, {col.Ident.Oid.Last()}, ..indexOid])] = {col.Ident.CSharpName()};"
            ),
            $"\treturn result;",
            $"}}"
        ];
    }

    public static string[] TableToValues(MibTable table)
    {
        return [
            $"public static IDictionary<Oid, AsnType> TableToValues({table.TableType()} entries)",
            $"{{",
            $"\tvar result = new Dictionary<Oid, AsnType>();",
            $"\tforeach (var entry in entries)",
            $"\t{{",
            $"\t\tforeach (var kv in entry.EntryToValues())",
            $"\t\t\tresult[kv.Key] = kv.Value;",
            $"\t}}",
            $"\treturn result;",
            $"}}"
        ];
    }

    
}