using System.Linq;

namespace SnmpSharpNet.Mib.SourceGenerator;

public static class Templating
{
    public static string[] DocComment(string content)
    {
        return
        [
            "/// <summary>",
            "/// Generated by SnmpSharpNet.Mib.SourceGenerator",
            $"/// {content}",
            "/// </summary>"
        ];
    }

    public static string[] TableEntry(string accessibility, MibTable table)
    {
        var typeName = table.EntryType();
        var strip = typeName.Replace("TableEntry", string.Empty);
        return
        [
            "",
            $"{accessibility} class {typeName} : ISnmpTableEntry<{typeName}>",
            "{",
            $"\tpublic static Oid Root => field ??= {table.Ident.AsLiteral()};",
            .. table.Index.SelectMany((idx, i) => (string[])
            [
                "",
                .. DocComment($"Index #{i + 1}"),
                $"public required {idx.Type.AsUintType()} Index{idx.Ident.CSharpName(strip)};",
            ]).Indent(),
            "",
            /*$"",
            $"\tpublic required uint[] index;",
            $"",*/
            .. table.Columns.SelectMany((col, i) => (string[])
            [
                "",
                .. DocComment($"Column #{i + 1}"),
                $"public required {col.Type.AsAsnType()} {col.Ident.CSharpName(strip)};",
            ]).Indent(),
            "",
            .. EntryFromValues(table).Indent(),
            "",
            .. TableFromValues(table).Indent(),
            "",
            .. EntryToValues(table).Indent(),
            "",
            .. TableToValues(table).Indent(),
            "}"
        ];
    }

    public static string[] EntryFromValues(MibTable table)
    {
        var typeName = table.EntryType();
        var strip = typeName.Replace("TableEntry", string.Empty);
        var indexPart = table.Index.SelectMany((index, _) =>
        {
            if (index.IsImplied && index.Type.UintCount is null)
            {
                // IMPLIED: no length prefix, consume the rest of the index span
                return (string[])
                [
                    $"var index{index.Ident.CSharpName(strip)} = ({index.Type.AsUintType()})index.ToArray();",
                    "index = default;"
                ];
            }

            return index.Type.UintCount switch
            {
                null =>
                [
                    $"var index{index.Ident.CSharpName(strip)} = ({index.Type.AsUintType()})index[1..(int)(1+index[0])].ToArray();",
                    "index = index[(int)(1+index[0])..];"
                ],
                1 => [$"var index{index.Ident.CSharpName(strip)} = index[0];", "index = index[1..];"],
                _ => (string[])
                [
                    $"var index{index.Ident.CSharpName(strip)} = ({index.Type.AsUintType()})index[..(int){index.Type.UintCount}].ToArray();",
                    $"index = index[(int){index.Type.UintCount}..];"
                ]
            };
        });


        return
        [
            $"public static {typeName}? EntryFromValues(ReadOnlySpan<uint> index, IReadOnlyDictionary<uint, AsnType> values)",
            "{",
            .. indexPart.Indent(),
            "",
            .. table.Columns.SelectMany((col, i) => (string[])
            [
                $"if(!values.TryGetValue({col.Ident.Oid.Last()}, out var _{col.Ident.CSharpName(strip)})) {{ return null; }}",
                $"if(_{col.Ident.CSharpName(strip)} is not {col.Type.AsAsnType()} {col.Ident.CSharpName(strip)}) {{ return null; }}",
            ]).Indent(),
            "",
            $"\treturn new {typeName}()",
            "\t{",
            .. table.Index.Select(x =>
                $"\t\tIndex{x.Ident.CSharpName(strip)} = index{x.Ident.CSharpName(strip)},"),
            .. table.Columns.Select(x =>
                $"\t\t{x.Ident.CSharpName(strip)} = {x.Ident.CSharpName(strip)},"),
            "\t};",
            "}"
        ];
    }

    public static string[] TableFromValues(MibTable table)
    {
        var typeName = table.EntryType();
        var hasVariableLengthIndex = table.Index.Any(x => x.Type.UintCount is null);
        // For fixed-length indexes we can compute the exact expected OID depth.
        // For variable-length indexes (OctetString, OID, etc.) the depth varies
        // per row, so we only require that the OID is longer than entry+column.
        var depthCheck = hasVariableLengthIndex
            ? "\tvar minDepth = entryDepth + 2;" // at least column + 1 index component
            : $"\tvar minDepth = entryDepth + 1 + {table.Index.Sum(x => x.Type.UintCount!.Value)};";

        return
        [
            $"public static {table.TableType()} TableFromValues(IReadOnlyDictionary<Oid, AsnType> values)",
            "{",
            "\t// OID layout: Root.1.<column>.<index...>",
            "\tvar entryDepth = Root.Length + 1;",
            depthCheck,
            "\tvar relevantValues = values",
            "\t\t.Where(kv => kv.Key.Length >= minDepth && Root.IsRootOf(kv.Key));",
            "",
            "\tvar entries = new Dictionary<Oid, Dictionary<uint, AsnType>>();",
            "",
            "\tforeach (var kv in relevantValues)",
            "\t{",
            "\t\tvar path = kv.Key.ToArray();",
            "\t\tvar column = path[entryDepth];",
            "\t\tvar index = new Oid(path[(entryDepth + 1)..]);",
            "\t\tif (!entries.ContainsKey(index))",
            "\t\t{",
            "\t\t\tentries[index] = new();",
            "\t\t}",
            "\t\tentries[index].Add(column, kv.Value);",
            "\t}",
            "",
            "\treturn entries",
            "\t\t.Select(x => EntryFromValues((uint[])x.Key, x.Value))",
            $"\t\t.OfType<{typeName}>()",
            "\t\t.ToArray();",
            "}"
        ];
    }

    public static string[] EntryToValues(MibTable table)
    {
        var typeName = table.EntryType();
        var strip = typeName.Replace("TableEntry", string.Empty);
        var indexParts = table.Index.SelectMany(index =>
        {
            if (index.IsImplied && index.Type.UintCount is null)
            {
                // IMPLIED: no length prefix
                return (string[])
                [
                    $"indexOid.AddRange(Index{index.Ident.CSharpName(strip)});"
                ];
            }

            return index.Type.UintCount switch
            {
                null =>
                [
                    $"indexOid.Add((uint)Index{index.Ident.CSharpName(strip)}.Length);",
                    $"indexOid.AddRange(Index{index.Ident.CSharpName(strip)});"
                ],
                1 => [$"indexOid.Add(Index{index.Ident.CSharpName(strip)});"],
                _ => (string[])[$"indexOid.AddRange(Index{index.Ident.CSharpName(strip)});"]
            };
        });

        return
        [
            "public IDictionary<Oid, AsnType> EntryToValues()",
            "{",
            "\tvar indexOid = new List<uint>();",
            .. indexParts.Indent(),
            "\tvar result = new Dictionary<Oid, AsnType>();",
            .. table.Columns.Select(col =>
                $"\tresult[new Oid((uint[])[..Root, 1, {col.Ident.Oid.Last()}, ..indexOid])] = {col.Ident.CSharpName(strip)};"
            ),
            "\treturn result;",
            "}"
        ];
    }

    public static string[] TableToValues(MibTable table)
    {
        return
        [
            $"public static IDictionary<Oid, AsnType> TableToValues({table.TableType()} entries)",
            "{",
            "\tvar result = new Dictionary<Oid, AsnType>();",
            "\tforeach (var entry in entries)",
            "\t{",
            "\t\tforeach (var kv in entry.EntryToValues())",
            "\t\t\tresult[kv.Key] = kv.Value;",
            "\t}",
            "\treturn result;",
            "}"
        ];
    }
}