
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

namespace SnmpSharpNet.Mib.SourceGenerator;

public static class Templating
{
    public static string Attributes =
        """
        #pragma warning disable CS9113
        using System;

        namespace SnmpSharpNet.Mib.Attributes
        {
            [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
            [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
            public sealed class MibModulesAttribute(params string[] modules) : Attribute {}

            [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
            [AttributeUsage(AttributeTargets.Class)]
            public sealed class MibOidsAttribute(params string[] modules) : Attribute {}
        }
        #pragma warning restore CS9113
        """;

    public static string[] DocComment(string content)
    {
        return [
            $"/// <summary>",
            $"/// Generated by SnmpSharpNet.Mib.SourceGenerator",
            $"/// {content}",
            $"/// </summary>"
        ];
    }

    public static string[] DataFile(IEnumerable<(PartialClass, ImmutableArray<MibItem>)> decls)
    {
        return [
            $"#nullable enable",
            $"using System;",
            $"using System.Linq;",
            $"using System.Collections.Generic;",
            $"using SnmpSharpNet;",
            $"",
            ..decls.SelectMany(x => PartialClass(x.Item1, x.Item2))
        ];
    }

    public static string[] PartialClass(PartialClass decl, IEnumerable<MibItem> items)
    {
        return decl.AsLiteral($": IOidGroup<{decl.TypeName}>", [
            ..items.OfType<MibTable>().SelectMany(x => TableEntry(decl.Accessibility, x)),
            $"",
            ..items.OfType<MibValuedItem>().SelectMany(OidField),
            $"",
            ..items.OfType<MibValuedItem>().SelectMany(ValueField),
            $"",
            $"",
            $"public static IEnumerable<Oid> SimpleOids {{ get; }} = [",
            ..items.OfType<MibLeaf>().Select(
                item => $"\t{item.Ident.Name}Oid,"
            ),
            $"];",
            $"",
            $"public static IEnumerable<Oid> BatchOids {{ get; }} = [",
            ..items.OfType<MibTable>().Select(
                item => $"\t{item.Ident.Name}Oid,"
            ),
            $"];",
            $"",
            ..FromValues(decl.TypeName, items)
        ]);
    }

    public static string[] OidField(MibValuedItem item)
    {
        var oid = item is MibTable ? item.Ident : item.Ident.ScalarInstance();
        return [
            $"",
            $"/// <summary>",
            $"/// From SNMP Mib",
            $"/// {item.Ident}",
            $"/// </summary>",
            $"public static readonly Oid {item.Ident.Name}Oid = {oid.AsLiteral()};",
        ];
    }
    public static string[] ValueField(MibValuedItem item)
    {
        return [
            $"",
            $"/// <summary>",
            $"/// From SNMP Mib",
            $"/// {item.Ident}",
            $"/// </summary>",
            item is MibTable table
                ? $"public {table.TableType()} {item.Ident.Name} = [];"
                : $"public AsnType {item.Ident.Name} = new NoSuchInstance();" 
        ];
    }

    public static string[] TableEntry(string accessibility, MibTable table)
    {
        return [
            $"",
            $"{accessibility} class {table.EntryType()}",
            $"{{",
            $"\tpublic static readonly Oid TableRoot = {table.Ident.AsLiteral()};",
            ..table.Index.SelectMany((idx, i) => (string[])[
                $"",
                ..DocComment($"Index #{i+1}"),
                $"public required {idx.Type.AsUintType()} index{idx.Ident.Name};",
            ]).Indent(),
            $"",
            /*$"",
            $"\tpublic required uint[] index;",
            $"",*/
            ..table.Columns.SelectMany((col, i) => (string[])[
                $"",
                ..DocComment($"Column #{i+1}"),
                $"public required {col.Type.AsAsnType()} {col.Ident.Name};",
            ]).Indent(),
            $"",
            ..EntryFromValues(table).Indent(),
            $"",
            ..TableFromValues(table).Indent(),
            $"}}"
        ];
    }

    public static string[] EntryFromValues(MibTable table)
    {
        var indexPart = table.Index.SelectMany((index, i) => {
            if (index.Type.UintCount is null)
            {
                return (string[])[
                    $"var index{index.Ident.Name} = ({index.Type.AsUintType()})index[1..(int)(1+index[0])].ToArray();",
                    $"index = index[(int)index[0]..];"
                ];
            }
            else if (index.Type.UintCount == 1)
            {
                return (string[])[
                    $"var index{index.Ident.Name} = index[0];",
                    $"index = index[1..];"
                ];
            }
            else
            {
                return (string[])[
                    $"var index{index.Ident.Name} = ({index.Type.AsUintType()})index[..(int){index.Type.UintCount}]).ToArray();",
                    $"index = index[(int){index.Type.UintCount}..];"
                ];
            }
        });



        return [
            $"public static {table.EntryType()}? EntryFromValues(ReadOnlySpan<uint> index, IReadOnlyDictionary<uint, AsnType> values)",
            $"{{",
            ..indexPart.Indent(),
            $"",
            ..table.Columns.SelectMany((col, i) => (string[])[
                $"if(!values.TryGetValue({col.Ident.Oid.Last()}, out var _{col.Ident.Name})) {{ return null; }}",
                $"if(_{col.Ident.Name} is not {col.Type.AsAsnType()} {col.Ident.Name}) {{ return null; }}",
            ]).Indent(),
            $"",
            $"\treturn new {table.EntryType()}()",
            $"\t{{",
            ..table.Index.Select(x => $"\t\tindex{x.Ident.Name} = index{x.Ident.Name},"),
            ..table.Columns.Select(x => $"\t\t{x.Ident.Name} = {x.Ident.Name},"),
            $"\t}};",
            $"}}"
        ];
    }

    public static string[] TableFromValues(MibTable table)
    {
        return [
            $"public static {table.TableType()} TableFromValues(IReadOnlyDictionary<Oid, AsnType> values)",
            $"{{",
            $"\t// OID layout: TableRoot.1.<column>.<index...>",
            $"\tvar entryDepth = TableRoot.Length + 1;",
            $"\tvar expectedDepth = entryDepth + 1 + {table.Index.Sum(x => x.Type.UintCount ?? 1)};",
            $"\tvar relevantValues = values",
            $"\t\t.Where(kv => kv.Key.Length >= expectedDepth && TableRoot.IsRootOf(kv.Key));",
            $"",
            $"\tvar entries = new Dictionary<Oid, Dictionary<uint, AsnType>>();",
            $"",
            $"\tforeach (var kv in relevantValues)",
            $"\t{{",
            $"\t\tvar path = kv.Key.ToArray();",
            $"\t\tvar column = path[entryDepth];",
            $"\t\tvar index = new Oid(path[(entryDepth + 1)..]);",
            $"\t\tif (!entries.ContainsKey(index))",
            $"\t\t{{",
            $"\t\t\tentries[index] = new();",
            $"\t\t}}",
            $"\t\tentries[index].Add(column, kv.Value);",
            $"\t}}",
            $"",
            $"\treturn entries",
            $"\t\t.Select(x => EntryFromValues((uint[])x.Key, x.Value))",
            $"\t\t.OfType<{table.EntryType()}>()",
            $"\t\t.ToArray();",
            $"}}"
        ];
    }


    public static string[] FromValues(string type, IEnumerable<MibItem> items)
    {
        return [
            $"public static {type}? FromValues(IReadOnlyDictionary<Oid, AsnType> values)",
            $"{{",
            $"\tvar value = new {type}();",
            ..items.OfType<MibLeaf>().Select(
                x => $"\tif(values.TryGetValue({x.Ident.Name}Oid, out var _{x.Ident.Name})) {{ value.{x.Ident.Name} = _{x.Ident.Name}; }}"
            ),
            ..items.OfType<MibTable>().Select(
                x => $"\tvalue.{x.Ident.Name} = {x.Ident.Name}Entry.TableFromValues(values);"
            ),
            $"",
            $"\treturn value;",
            $"}}",
        ];
    }

    
}