name: Docker Image CI

on:
  push:
    branches: [ wmo ]
  pull_request:
    branches: [ wmo ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag westermo/snmpsharpnet && docker run --rm -t westermo/snmpsharpnet
