name: Publish NuGet

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and publish NuGet
      run: docker build -t westermo/snmpsharp-nuget -f ./PublishNuget.dockerfile . && docker run --rm -e "NUGET_TOKEN=${GITHUB_TOKEN}" -it westermo/snmpsharp-nuget
